### ISSUE TITLE
[Android] Return notification body with notification id

### ISSUE THREAD

**Issue by aogilvie** [Wizcorp/phonegap-plugin-localNotifications#10]
Return notification body with notification id to match iOS spec.

**Comment by StasKalishenko** [comment]
It really doesn't work on Android. Guys, how to get notification (or any option of it) in app on Android? Is it possible? It works only on iOS. I figured out how to open an app tapping on local notification but "receivedLocalNotification" event is not firing.

**Comment by aogilvie** [comment]
Fixed: https://github.com/Wizcorp/phonegap-plugin-localNotifications/commit/c6a68cbc5025b34a213a787a5ed96e09d5448cf1
For more information try the Android sample application.

**Comment by StasKalishenko** [comment]
Great! But what about opening closed app? Moreover, more useful to get alarm in app when user exactly taps on notification but not when notification only appears. Is it possible?
