### ISSUE TITLE
Update for 3.0 or above to use with CLI?

### ISSUE THREAD

**Issue by walidinho99** [Wizcorp/phonegap-plugin-localNotifications#11]
Hi there, will anyone update this great plugin so we can use it with the CLI install for 3.0+?

**Comment by aogilvie** [comment]
Yes! However, i'm rather busy right now. Will accept PRs, otherwise it's scheduled in about 1-2 weeks...

**Comment by walidinho99** [comment]
That is just awesome! Its been working great for our hybrid app, and would hate to move to another plugin.  This one has been painless and lightweight.    I'll check back in couple weeks, thx a bunch for replying quickly.

**Comment by aogilvie** [comment]
@walidinho99 Give it a try :bowtie:

[https://github.com/Wizcorp/phonegap-plugin-localNotifications/tree/v3.0](https://github.com/Wizcorp/phonegap-plugin-localNotifications/tree/v3.0)

**Comment by walidinho99** [comment]
It's a beauty!   Plugman did its job, see extract from "cordova_plugins.js" below. Seamless thru iOS7 as advertised.

ZERO code changes.   Download/build/run and done.  

For those needing badge update, you cant beat local notification when pushNotifications give u fits.  Keep up the great work, much, much thx!

{
        "file": "plugins/jp.wizcorp.phonegap.plugin.localNotificationPlugin/www/phonegap/plugin/localNotification/localNotification.js",
        "id": "jp.wizcorp.phonegap.plugin.localNotificationPlugin.localNotificationPlugin",
        "clobbers": [
            "window.localNotification"
        ]
    }

**Comment by walidinho99** [comment]
Real quick....wanted to give an update.

iOS7 and Cordova playing police patrol, see below.  I think the plugin guide recommends to wrap it around a background thread.   Since it is just a warning, i wont worry about it for now...but heads up.  Thx again!

THREAD WARNING: ['LocalNotification'] took '11.623291' ms. Plugin should use a background thread.
2013-10-10 11:39:15.418 MyCSPMobile[223:60b]  Notification application badge set to: 6

**Comment by walidinho99** [comment]
Tested really well aside from the nasty warning from aboce comment....so ONE last thing i noticed.

Not sure you intended to add a 'plugin' xml data element thru the plugin.xml that was generated.

All other core plugins do not add that 'plugin' element...so maybe custom plugins have to do it. Not sure?

<config-file target="config.xml" parent="/*">
            <feature name="LocalNotification">
                <param name="ios-package" value="LocalNotification"/>
                <param name="onload" value="true" />
            </feature>
            <plugin name="LocalNotification" value="LocalNotification"/>
        </config-file>

**Comment by aogilvie** [comment]
@walidinho99  are you referring to: `<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"` ?

**Comment by walidinho99** [comment]
Was referring to this one below...if u expand my lsat comment, u will see it too.  In the generated config.xml agter 'build ios'.

<config-file target="config.xml" parent="/*">
            <feature name="LocalNotification">
                <param name="ios-package" value="LocalNotification"/>
                <param name="onload" value="true" />
            </feature>
            <plugin name="LocalNotification" value="LocalNotification"/>
        </config-file>

**Comment by walidinho99** [comment]
SO this is an excerpt off the plugin.xml that was generated after i built IOS platform, check that section.,…way below.

Perhaps the customized plugins retain the "plugin" xml element while the core plugins do not??

I don't think it s a big deal, because its working  beautifully
thx a bunch !!!!

<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android"
    id="jp.wizcorp.phonegap.plugin.localNotificationPlugin"
    version="1.0.0">

```
<name>Local Notification Plugin</name>

<description>This plugin allows you to add, queue, cancel by id and cancel all local notifications.</description>

<author>Ally Ogilvie - aogilvie@wizcorp.jp</author>

<keywords>local, notification, notifications</keywords>

<engines>
    <engine name="cordova" version=">=3.0.0" />
</engines>

<license>MIT</license>

<js-module src="www/phonegap/plugin/localNotification/localNotification.js" name="localNotificationPlugin" target="phonegap/plugin/localNotification/localNotification.js">
    <clobbers target="window.localNotification" />
</js-module>

<!-- android -->
<platform name="android">

<config-file target="res/xml/config.xml" parent="/*">
    <feature name="LocalNotification" >
        <param name="android-package" value="jp.wizcorp.phonegap.plugin.localNotification.LocalNotification"/>
    </feature>
</config-file>

<config-file target="AndroidManifest.xml" parent="/manifest">
    <uses-permission android:name="android.permission.VIBRATE" />
</config-file>   

<config-file target="AndroidManifest.xml" parent="/manifest/application">
    <receiver android:name="jp.wizcorp.phonegap.plugin.localNotification.AlarmReceiver" ></receiver>
    <receiver android:name="jp.wizcorp.phonegap.plugin.localNotification.AlarmRestoreOnBoot" >
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED" />
        </intent-filter>
    </receiver>
</config-file>

<source-file src="android/jp/wizcorp/phonegap/plugin/localNotification/LocalNotification.java" 
        target-dir="src/jp/wizcorp/phonegap/plugin/localNotification"/>
<source-file src="android/jp/wizcorp/phonegap/plugin/localNotification/AlarmHelper.java" 
        target-dir="src/jp/wizcorp/phonegap/plugin/localNotification"/> 
        <source-file src="android/jp/wizcorp/phonegap/plugin/localNotification/AlarmOptions.java" 
        target-dir="src/jp/wizcorp/phonegap/plugin/localNotification"/> 
        <source-file src="android/jp/wizcorp/phonegap/plugin/localNotification/AlarmReceiver.java" 
        target-dir="src/jp/wizcorp/phonegap/plugin/localNotification"/> 
        <source-file src="android/jp/wizcorp/phonegap/plugin/localNotification/AlarmRestoreOnBoot.java" 
        target-dir="src/jp/wizcorp/phonegap/plugin/localNotification"/> 
</platform>

<!-- ios -->
<platform name="ios">

    <config-file target="config.xml" parent="/*">
        <feature name="LocalNotification">
            <param name="ios-package" value="LocalNotification"/>
            <param name="onload" value="true" />
        </feature>
        <plugin name="LocalNotification" value="LocalNotification"/>
    </config-file>

    <!-- Plugin files -->
    <header-file src="ios/project/Plugins/LocalNotification/LocalNotification.h" />
    <source-file src="ios/project/Plugins/LocalNotification/LocalNotification.m" compiler-flags="-fno-objc-arc" />

    <!-- Custom Logger -->
    <header-file src="ios/project/Plugins/LocalNotification/WizDebugLog.h"
        target-dir="WizCanvas" />

</platform>

<license>MIT</license>
```

</plugin>

**Comment by aogilvie** [comment]
I've checked other plugin.xml files and this seems to be normal. Thanks for the feedback. Hope to look at fixing the threading warning soon (feel free to open a new issue for that if you wish).
