### ISSUE TITLE
Launch is undefined under iOS

### ISSUE THREAD

**Issue by jValdron** [Wizcorp/phonegap-plugin-localNotifications#15]
I'm trying to implement the `launch` callback, so that I can redirect the user to the proper page when he receives a notification, however, the `launch` function doesn't seem to exist, even in the plugin file it doesn't declare it. Is there an event I can use or something?

```
I get the following error: TypeError: 'undefined' is not a function (evaluating 'localNotification.launch')
```

**Comment by aogilvie** [comment]
Sorry the documentation is wrong I think. Please use:
`document.addEventListener("receivedLocalNotification", onReceivedLocalNotification, false);`

**Comment by aogilvie** [comment]
I've added example project. Here is the example project sample code:
https://github.com/Wizcorp/phonegap-plugin-localNotifications/blob/master/platforms/ios/www/index.html#L342
