### ISSUE TITLE
application crash when notification show

### ISSUE THREAD

**Issue by avishayhajbi** [Wizcorp/phonegap-plugin-localNotifications#17]
when notification show the application been crashed.
second the icon doesn't work, i wrote the path and it didn't do anything.
thanks

**Comment by aogilvie** [comment]
@avishayhajbi please provide; sample code, platform, log. etc.

**Comment by avishayhajbi** [comment]
i'm using cordova 3.5.0 
my code is : 
localNotification.add(103, {
    seconds: 60,
    title: "welcome",
    message: "have fun",
    icon: "img/logo.png",
    badge: 1});

the icon isn't show.. i have a star as icon
and when the notification activate i have a message that says:
"myAppName" has stopped

**Comment by aogilvie** [comment]
iOS or Android? I'm assuming Android.
Can you try the new Develop or Master branch? Try the sample application in `platforms/android/`

**Comment by avishayhajbi** [comment]
i'm tried .. it still have problem.
i'm update my last answer the app alert after firing notification : 
appName has stopped

**Comment by aogilvie** [comment]
Star is the default image. 
Currently Android reads the drawable name only.
`iconResource = cordova.getActivity().getResources().getIdentifier(icon, "drawable", cordova.getActivity().getPackageName());`

you should put your image (`logo.png`) in res/drawable and put this in options `icon: "logo",`

**Comment by aogilvie** [comment]
I'm unable to re-create your error. so please include your logcat output.

**Comment by avishayhajbi** [comment]
it works.  thanks.
It was my mistake. 
I'm wrote logo.png
thanks again.

**Comment by avishayhajbi** [comment]
it works.  thanks.
It was my mistake. 
I'm wrote logo.png
thanks again.
