### ISSUE TITLE
Receive notification in JavaScript from cold closed app state (Android)

### ISSUE THREAD

**Issue by aogilvie** [Wizcorp/phonegap-plugin-localNotifications#20]
Currently notification is only passed to JavaScript when application is still running in background.

Look into starting the application if closed with intent and telling JS about it.

**Comment by aogilvie** [comment]
#26 fixed

**Comment by tmaximini** [comment]
I see a 
`I/ActivityManager(  744): START u0 {cmp=my.app.com/jp.wizcorp.phonegap.plugin.localNotification.AlarmHelper (has extras)} from uid 10166 on display 0
W/InputMethodManagerService(  744): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2abfa570 attribute=null, token = android.os.BinderProxy@3a51fb8`

in logcat whenever I try to receive notification from cold closed app.
Anything I am missing here?
