### ISSUE TITLE
limited number of chars

### ISSUE THREAD

**Issue by avishayhajbi** [Wizcorp/phonegap-plugin-localNotifications#23]
i'm using cordova 3.0.5 and when i trigger notification with many chars it ignores the chars and the notification appear empty.

**Comment by aogilvie** [comment]
Please post sample code, length of the string and the platform you are using.

**Comment by aogilvie** [comment]
@avishayhajbi 
Is this for Android? I have tried long string in `title` and `message` setting without problems..

**Comment by aogilvie** [comment]
No reply. Closing.
