### ISSUE TITLE
Permissions asked before trying to set Notification

### ISSUE THREAD

**Issue by Antonio-Laguna** [Wizcorp/phonegap-plugin-localNotifications#31]
Hi here!

I've been implementing this plugin into my project and it does work like a charm! Thanks!

Besides this, I'd like to avoid prompting the user to give permission to the app, just on app load. The user doesn't really know why I am requesting that permission and it's likely that some people will just refuse because of that.

Is there any setting to fix this behaviour and ask for permission when trying to set up a notification?

**Comment by aogilvie** [comment]
If you want you can manually change this code:

Move this section: https://github.com/Wizcorp/phonegap-plugin-localNotifications/blob/master/platforms/ios/HelloCordova/Plugins/LocalNotification/LocalNotification.m#L87-L92

to the top of this function: https://github.com/Wizcorp/phonegap-plugin-localNotifications/blob/master/platforms/ios/HelloCordova/Plugins/LocalNotification/LocalNotification.m#L123

I hope that makes sense.
