### ISSUE TITLE
Icon not working

### ISSUE THREAD

**Issue by kunsachdeva** [Wizcorp/phonegap-plugin-localNotifications#38]
What am I supposed to write in icon property?
something like- icon:"icon.png" or icon:"http://sergeskor.no-ip.org/Files/Tech/correct.png"
Neither of them seem to work.
![screenshot_2015-12-30-00-42-08](https://cloud.githubusercontent.com/assets/5383258/12040357/72e24ac8-ae8e-11e5-9270-d8e216fbb3a9.png)
This is what I get no matter I set to icon property or even leave it undefined.

**Comment by jrouault** [comment]
Hello,
Please refer to the [README.md](https://github.com/Wizcorp/phonegap-plugin-localNotifications#addint-id-jsonobject-options-function-success-function-failure).

> The `icon` property has to reference to the name of a drawable resource in your Android project. If you leave the `title`, `ticker` or `icon` empty they will become default values.

Here is the doc for [drawable resource on Android](http://developer.android.com/guide/topics/resources/drawable-resource.html).
