### ISSUE TITLE
Support for 2.4+

### ISSUE THREAD

**Issue by BrandonBlanchard** [Wizcorp/phonegap-plugin-localNotifications#6]
How far off is this?

**Comment by aogilvie** [comment]
The updates required to a plugin are outlined here http://docs.phonegap.com/en/2.4.0/guide_upgrading_ios_index.md.html#Upgrading%20Cordova%20iOS we intend to update this and other plugins soon, but scheduling is not fixed yet.

I think for at least 2.4 support you should require very little, if any, changes to the plugin code.

**Comment by wcwynn** [comment]
Pull request #7 adds this support.

**Comment by aogilvie** [comment]
See branch v2.7.
